let stringVariable = "   Riyaz Khan   ";

console.log(stringVariable.charAt(4));
console.log(stringVariable.concat(" ", "Pathn"));
console.log(stringVariable.startsWith("R"));
console.log(stringVariable.startsWith("K"));
console.log(stringVariable.endsWith("z"));
console.log(stringVariable.endsWith("n"));
console.log(stringVariable.includes("A"));
console.log(stringVariable.includes("z"));
console.log(stringVariable.indexOf("a"));
console.log(stringVariable.lastIndexOf("a"));
console.log(stringVariable.match(/[A-Z]/g));
console.log(stringVariable.match(/[a-z]/g));
console.log(stringVariable.padStart(15, " ~"));
console.log(stringVariable.padStart(15, "~"));
console.log(stringVariable.padEnd(15, " ~"));
console.log(stringVariable.padEnd(15, "~"));
console.log(stringVariable.repeat(3));
console.log(stringVariable + "-".repeat(3));
console.log((stringVariable + "-").repeat(3));
console.log(stringVariable.replace("Khan", "Pathan"));
console.log(stringVariable.search("a"));
console.log(stringVariable.search("an"));
console.log(stringVariable.search("az"));
console.log(stringVariable.search("A"));
console.log(stringVariable.search("P"));
console.log((stringVariable + " Pathan").search("P"));
console.log(stringVariable.slice(4,6));
console.log(stringVariable.slice(4,9));
console.log(stringVariable.length);
console.log(stringVariable.split("a"));
console.log(stringVariable.split(""));
console.log(stringVariable.substring(4,6));
console.log(stringVariable.substring(4,9));
console.log(stringVariable.toLocaleLowerCase());
console.log(stringVariable.toLowerCase());
console.log(stringVariable.toLocaleUpperCase());
console.log(stringVariable.toUpperCase());
console.log(stringVariable.trim());
console.log(stringVariable.trimStart());
console.log(stringVariable.trimEnd());